### ISSUE TITLE
dataset path

### ISSUE THREAD

**Issue by FRANKJIANG20** [kschmeckpeper/rl_with_videos#2]
Dear sir,
     would you please tell me where is the dataset path in this code?

**Comment by kschmeckpeper** [comment]
The path to the action-free dataset can be set with the command line argument `--replay_pool_load_path /PATH/TO/REPLAY/POOL` while the path to the paired data can be set with the command line argument `--paired_data_path /PATH/TO/PAIRED/DATA`.  

The datasets that we used in the experiments in the paper are available on the website, [here](https://sites.google.com/view/rl-with-videos).

**Comment by FRANKJIANG20** [comment]
Thanks a lot!  Another question is what does --exp-name EXP_NAME mean?

**Comment by kschmeckpeper** [comment]
`--exp-name` sets the name that the results from the experiment will be saved under.  The name of the folder will be formatted something like Timestamp-EXP_NAME-seed=SEED, so you can run multiple experiments with the same exp-name.

**Comment by FRANKJIANG20** [comment]
Thank you very much!

**Comment by kschmeckpeper** [comment]
Glad to help!
