### ISSUE TITLE
The problems of mujoco

### ISSUE THREAD

**Issue by FRANKJIANG20** [kschmeckpeper/rl_with_videos#3]
Dear sir,
    I am so sory to ask you some questions again for this code.When I run this code the terminal stop
carried out.And I search the files in ray_results,then I find a MUJOCOLOG.TXT,which writing that 'ERROR: GLEW initalization error: Missing GL version'.
    I can run some other codes in mujoco env and I tried some solutions but I have not solve this problems.
    If you have some idea to help me solve this problems,I will appreciate it.

**Comment by kschmeckpeper** [comment]
Do you have all of your environment variables set up correctly for mujoco?

This might be the solution.
https://github.com/openai/mujoco-py/issues/268

**Comment by FRANKJIANG20** [comment]
> Do you have all of your environment variables set up correctly for mujoco?
> 
> This might be the solution.
> [openai/mujoco-py#268](https://github.com/openai/mujoco-py/issues/268)

Thank you for your instrution.I have already solved problems aftering replacing my ubuntu20.04 system with ubuntu18.04.
