### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by FRANKJIANG20** [kschmeckpeper/rl_with_videos#4]
Dear sir,
     I am so sorry to bother you again for some questions.could you tell me the function of each part in scripts.And how can I to run this .py file,in other words,what should I input in command line?

**Comment by kschmeckpeper** [comment]
Most of the python files in the `scripts` folder are for manipulating replay pools, generating plots, or other secondary tasks.  If you want to run the experiments, you should instead use main.py in `examples/run_rl`, with the arguments described [here](https://github.com/kschmeckpeper/rl_with_videos#examples).

**Comment by FRANKJIANG20** [comment]
I don't know how to run the visualization phenomenon. Which module in the code is responsible for processing video and image data. When the training is over, how to use the generated manipulating replay pools to make the manipulator in mujoco operate and generate visual phenomenon.Thank you very much!

**Comment by kschmeckpeper** [comment]
We use tensorboard to visualize the training curves, so once your code is training, you can start a tensorboard session in a different terminal with a command like this. `tensorboard --logdir /PATH/TO/LOGS`.

You can also generate videos of the training using the `--video-save-frequency` when starting the training to specify how frequently the videos should be saved during training.

Finally, the script `vis_replay_pool.py` will save frames from your replay pool, but that script is set to save a random selection of frames, so depending on your goal, you may want to modify it before using it.

**Comment by FRANKJIANG20** [comment]
Thank you for your guidance, I have run the **vis_replay_pool.py** script and checked the effect. But I didn't figure out how to use the **--video-save-frequency** you mentioned and how to run mujoco in this code. I do not make sure whether I should use the py file in    **rl_with_videos/src/metaworld/metaworld/envs/mujoco/utils**?
Many thanks!

**Comment by kschmeckpeper** [comment]
In order to use the option --video-save-frequency, you would run something like 
`cd examples/run_rl
python3 main.py OTHER_OPTIONS --video-save-frequency 10`
This would cause it to save videos every 10 epochs during training.

All the options that you can use during training are defined in `examples/run_rl/utils.py`.
