### ISSUE TITLE
Dataset links

### ISSUE THREAD

**Issue by minttusofia** [kschmeckpeper/rl_with_videos#5]
I found a couple of minor issues with the datasets.

The first two Acrobot replay pool links point to the same file. It seems that the medium-performance pool is the one that is missing.

Secondly, the paired frame datasets linked to from the Github readme and the project website are slightly different. The latter actually includes slightly fewer paired frames for pushing. Has the one of the website been intentionally filtered?

**Comment by kschmeckpeper** [comment]
Thanks for noticing these!  I pushed the correct acrobot replay pool link for the medium performance pool.

The paired frame dataset from github is the correct one.  I've fixed the one on the website.
