### ISSUE TITLE
Low evaluation and training returns after 130 epochs

### ISSUE THREAD

**Issue by IrohXu** [kschmeckpeper/rl_with_videos#7]
Hi, kschmeckpeper:

Thanks for your great work. I am trying to run RLV on my RTX 2080Ti, but after 130 epochs of training, the training and evaluation return is still 0. The task is `Image48HumanLikeSawyerPushForwardEnv-v0`. I do not change any parameter during training. Here is the output table: [progress2.csv](https://github.com/kschmeckpeper/rl_with_videos/files/7522601/progress2.csv)
The seed is 8898

And I also have a small question on this project: do you have any suggested random seed for training? I am trying to find a path achieving similar result from your paper.

,Best

**Comment by kschmeckpeper** [comment]
The results in the paper were from averaging together the results from running 10 different seeds.  In general, on the human data, about a third of the seeds would fail to get non-zero reward, so your results are not unexpected.  

Unfortunately, I can't seem to find the seeds that I used.  I would suggest running it a couple more times.  If you are still not getting good results, please post the command you are running and I can try to debug.

**Comment by IrohCao-NYU** [comment]
> The results in the paper were from averaging together the results from running 10 different seeds. In general, on the human data, about a third of the seeds would fail to get non-zero reward, so your results are not unexpected.
> 
> Unfortunately, I can't seem to find the seeds that I used. I would suggest running it a couple more times. If you are still not getting good results, please post the command you are running and I can try to debug.

Thanks for your reply. I am trying to run the code with different seeds. Hope it can work.

,Best

**Comment by IrohXu** [comment]
Hi, kschmeckpeper:

I noticed you update the paper with removing the pair loss. To draw the figures in your research, do you use the data from zero reward?

Thank you!

Iroh

**Comment by IrohXu** [comment]
Hi, kschmeckpeper:

I noticed you update the paper with removing the pair loss. To draw the figures in your research, do you use the data from zero reward?

Thank you!

Iroh

**Comment by kschmeckpeper** [comment]
We removed the pair loss from the paper because we noticed a bug that caused the paired data to be unused in all of our experiments.  

Which figures are you referring to?
