### ISSUE TITLE
Question on original inpute videos and images in .pkl file

### ISSUE THREAD

**Issue by IrohXu** [kschmeckpeper/rl_with_videos#8]
Hi, kschmeckpeper:

I have checked the .pkl you provided for training. It seems that the size of image in the .pkl is different from the original video. Do you use any transformations like crop that generate the replay pool pkl files from human videos?
The image inside .pkl is like this:
![image](https://user-images.githubusercontent.com/40520605/143663461-0dd4d637-8740-44a9-9e0b-4613186251e9.png)

The image from videos is like this:
![image](https://user-images.githubusercontent.com/40520605/143663490-72389655-43c2-445f-a8c7-dbd12b16c492.png)

Thank you!
Iroh

**Comment by kschmeckpeper** [comment]
The images were warped and cropped to align the locations of the black squares.  Here is the script that I used to do the preprocessing.

```
from __future__ import print_function

import cv2
import numpy as np
from os.path import join, isfile, isdir
from os import listdir, makedirs


import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.animation as animation
import matplotlib.patches as patches

import argparse

def visualize(i):
    pass

class ImageAligner():
    def __init__(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('in_path', type=str)
        parser.add_argument('out_path', type=str)
        parser.add_argument('--single_point', action='store_true', dest='single_point')
        args = parser.parse_args()
        self.in_path = args.in_path
        self.out_path = args.out_path
        # Top left, top right, bottom right, bottom left
        self.goal_points = [[20.5, 11.5], [26.5, 11.5], [26.5, 16.5], [20.5, 16.5]]
        self.fraction_to_keep = 1

        self.file_names = [f for f in listdir(self.in_path) if isfile(join(self.in_path, f))]
        self.single_point = args.single_point

        if args.single_point:
            self.goal_points = [[32.0, 27.0]]


        print("values:", self.file_names)
        self.index = -1
        self.points = []

        self.fig, self.ax = plt.subplots()
        self.fig.canvas.callbacks.connect('button_press_event', self.clickCallback)
        ani = animation.FuncAnimation(self.fig, visualize, interval=50)
        self.update_image()

        plt.show()

        plt.close()

    def clickCallback(self, event):
        print("Clicked: ({}, {})".format(event.xdata, event.ydata))
        

        x = max(0, min(event.xdata, self.img_shape[1]))
        y = max(0, min(event.ydata, self.img_shape[0]))

        self.points.append([x, y])
        if len(self.points) == 4 or self.single_point:
            self.align_images()
            self.update_image()

    def align_images(self):
        print("points:", self.points)
        print("goal points:", self.goal_points)
        src_points = np.array(self.points).astype(np.float32)
        dst_points = np.array(self.goal_points).astype(np.float32)

        if not self.single_point:
            warp_matrix = cv2.getPerspectiveTransform(src_points, dst_points)
        else:
            diff =  np.mean(dst_points, axis=0) - (src_points[0] / np.array([1080, 1920]) * np.array([48, 85]))
            print(self.current_frames[0].shape)
            print(diff)

            warp_matrix = np.float32([[1, 0, diff[0]], [0, 1, diff[1]]])
            # warp_matrix = np.float32([[1, 0, 0], [0, 1, 10]])
        # print("warp_matrix", warp_matrix)
            # +x  to the right
            # +y down
        split = "train"
        if self.index % 10 == 0:
            split = "test"

        for i in range(len(self.current_frames)):
            if not self.single_point:
                warped_frame = cv2.warpPerspective(self.current_frames[i], warp_matrix, (48, 85))
            else:
                self.current_frames[i] = cv2.resize(self.current_frames[i], (48, 85))
                warped_frame = cv2.warpAffine(self.current_frames[i], warp_matrix, (48, 85))
                
            # print("warped_frame.shape", warped_frame.shape)
            # cv2.imwrite("full_warped_frame.png", warped_frame)
            # cv2.imwrite(join(self.out_path, split, "video_{:04d}_frame_{:04d}.png".format(self.index, i)), warped_frame[:48, :, :])
            cv2.imwrite(join(self.out_path, "video_{:04d}_frame_{:04d}.png".format(self.index, i)), warped_frame[:48, :, :])


    def get_frames_from_video(self):
        current_frames = []

        cap = cv2.VideoCapture(join(self.in_path, self.file_names[self.index]))

        fourcc = cv2.VideoWriter_fourcc(*'MJPG')
        i = 0
        while cap.isOpened():  
            ret, frame = cap.read()
            i += 1
            if i % self.fraction_to_keep != 0:
                continue
            if not ret:
                break
            
            # frame = frame[:, -frame.shape[0]:, :]
            # frame = cv2.resize(frame, (48, 48))
            # frame = cv2.rotate(frame, cv2.ROTATE_90_COUNTERCLOCKWISE)
            frame = cv2.rotate(frame, cv2.ROTATE_90_CLOCKWISE)
            frame = frame[:, ::-1, :]
            current_frames.append(frame)
        return current_frames

    def update_image(self):
        self.index += 1

        self.points = []

        if self.index >= len(self.file_names):
            print("Finished")
            exit()

        print("self.file_names:", self.index, len(self.file_names), self.file_names[self.index])
        self.current_frames = self.get_frames_from_video()
        self.ax.clear()

        print("len current_frames:", len(self.current_frames))
        img = self.current_frames[0]
        self.img_shape = img.shape  
        imgplot = self.ax.imshow(img)



if __name__ == '__main__':
    ia = ImageAligner()
```

**Comment by IrohXu** [comment]
> The images were warped and cropped to align the locations of the black squares. Here is the script that I used to do the preprocessing.
> 
> ```
> from __future__ import print_function
> 
> import cv2
> import numpy as np
> from os.path import join, isfile, isdir
> from os import listdir, makedirs
> 
> 
> import matplotlib.pyplot as plt
> import matplotlib.image as mpimg
> import matplotlib.animation as animation
> import matplotlib.patches as patches
> 
> import argparse
> 
> def visualize(i):
>     pass
> 
> class ImageAligner():
>     def __init__(self):
>         parser = argparse.ArgumentParser()
>         parser.add_argument('in_path', type=str)
>         parser.add_argument('out_path', type=str)
>         parser.add_argument('--single_point', action='store_true', dest='single_point')
>         args = parser.parse_args()
>         self.in_path = args.in_path
>         self.out_path = args.out_path
>         # Top left, top right, bottom right, bottom left
>         self.goal_points = [[20.5, 11.5], [26.5, 11.5], [26.5, 16.5], [20.5, 16.5]]
>         self.fraction_to_keep = 1
> 
>         self.file_names = [f for f in listdir(self.in_path) if isfile(join(self.in_path, f))]
>         self.single_point = args.single_point
> 
>         if args.single_point:
>             self.goal_points = [[32.0, 27.0]]
> 
> 
>         print("values:", self.file_names)
>         self.index = -1
>         self.points = []
> 
>         self.fig, self.ax = plt.subplots()
>         self.fig.canvas.callbacks.connect('button_press_event', self.clickCallback)
>         ani = animation.FuncAnimation(self.fig, visualize, interval=50)
>         self.update_image()
> 
>         plt.show()
> 
>         plt.close()
> 
>     def clickCallback(self, event):
>         print("Clicked: ({}, {})".format(event.xdata, event.ydata))
>         
> 
>         x = max(0, min(event.xdata, self.img_shape[1]))
>         y = max(0, min(event.ydata, self.img_shape[0]))
> 
>         self.points.append([x, y])
>         if len(self.points) == 4 or self.single_point:
>             self.align_images()
>             self.update_image()
> 
>     def align_images(self):
>         print("points:", self.points)
>         print("goal points:", self.goal_points)
>         src_points = np.array(self.points).astype(np.float32)
>         dst_points = np.array(self.goal_points).astype(np.float32)
> 
>         if not self.single_point:
>             warp_matrix = cv2.getPerspectiveTransform(src_points, dst_points)
>         else:
>             diff =  np.mean(dst_points, axis=0) - (src_points[0] / np.array([1080, 1920]) * np.array([48, 85]))
>             print(self.current_frames[0].shape)
>             print(diff)
> 
>             warp_matrix = np.float32([[1, 0, diff[0]], [0, 1, diff[1]]])
>             # warp_matrix = np.float32([[1, 0, 0], [0, 1, 10]])
>         # print("warp_matrix", warp_matrix)
>             # +x  to the right
>             # +y down
>         split = "train"
>         if self.index % 10 == 0:
>             split = "test"
> 
>         for i in range(len(self.current_frames)):
>             if not self.single_point:
>                 warped_frame = cv2.warpPerspective(self.current_frames[i], warp_matrix, (48, 85))
>             else:
>                 self.current_frames[i] = cv2.resize(self.current_frames[i], (48, 85))
>                 warped_frame = cv2.warpAffine(self.current_frames[i], warp_matrix, (48, 85))
>                 
>             # print("warped_frame.shape", warped_frame.shape)
>             # cv2.imwrite("full_warped_frame.png", warped_frame)
>             # cv2.imwrite(join(self.out_path, split, "video_{:04d}_frame_{:04d}.png".format(self.index, i)), warped_frame[:48, :, :])
>             cv2.imwrite(join(self.out_path, "video_{:04d}_frame_{:04d}.png".format(self.index, i)), warped_frame[:48, :, :])
> 
> 
>     def get_frames_from_video(self):
>         current_frames = []
> 
>         cap = cv2.VideoCapture(join(self.in_path, self.file_names[self.index]))
> 
>         fourcc = cv2.VideoWriter_fourcc(*'MJPG')
>         i = 0
>         while cap.isOpened():  
>             ret, frame = cap.read()
>             i += 1
>             if i % self.fraction_to_keep != 0:
>                 continue
>             if not ret:
>                 break
>             
>             # frame = frame[:, -frame.shape[0]:, :]
>             # frame = cv2.resize(frame, (48, 48))
>             # frame = cv2.rotate(frame, cv2.ROTATE_90_COUNTERCLOCKWISE)
>             frame = cv2.rotate(frame, cv2.ROTATE_90_CLOCKWISE)
>             frame = frame[:, ::-1, :]
>             current_frames.append(frame)
>         return current_frames
> 
>     def update_image(self):
>         self.index += 1
> 
>         self.points = []
> 
>         if self.index >= len(self.file_names):
>             print("Finished")
>             exit()
> 
>         print("self.file_names:", self.index, len(self.file_names), self.file_names[self.index])
>         self.current_frames = self.get_frames_from_video()
>         self.ax.clear()
> 
>         print("len current_frames:", len(self.current_frames))
>         img = self.current_frames[0]
>         self.img_shape = img.shape  
>         imgplot = self.ax.imshow(img)
> 
> 
> 
> if __name__ == '__main__':
>     ia = ImageAligner()
> ```

Thanks a lot!
