### ISSUE TITLE
simulation environment

### ISSUE THREAD

**Issue by gautica** [kschmeckpeper/rl_with_videos#9]
Hi,
thank you for your great work. I would like to run your code but I cannot find the robot model pusher_2d.xml in your project. Is it published? thank you very much.

**Comment by kschmeckpeper** [comment]
I'm not sure what file that is off of the top of my head.  What command are you trying to run?  Could you give me the full error message?

**Comment by gautica** [comment]
sorry, I didn't install all requirements and found that you were downloading metaworld and multiworld environments into your project. Thank you
